name: Build

on:
  workflow_call:
    inputs:
      node-version:
        default: "16"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      # Needed to get Workspaces in Node 14
      - name: Upgrade NPM
        if: ${{ github.events.inputs.node-version != 16 }}
        run: npm i -g npm

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Build node-canvas libraries
        run: docker build -t canvas-libs .

      - name: Inject libraries
        run: |
          id=$(docker create canvas-libs)
          docker cp $id:/root/dist ./packages/create-map
          docker cp $id:/root/dist ./packages/add-token
          docker cp $id:/root/dist ./packages/move-delete-token
          docker rm -v $id

      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: packages/**/dist/
