name: Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: api
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Set up Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r api/dev_requirements.txt
          pip install -r api/requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Build client application
        run: |
          cd client
          npm ci
          npm run build
          npm run build:package

      - name: Test with unittest
        run: |
          python -m unittest

      - name: Test client with jest
        run: |
          cd client
          npm run test:coverage

      - name: Archive Client package
        uses: actions/upload-artifact@v2
        with:
          name: carto-client
          path: client/package

  deploy:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployment
    env:
      DOCKER_REPO: api
      DOCKER_TAG: latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}

      - name: Download Client Artifact
        uses: actions/download-artifact@v2
        with:
          name: carto-client
          path: client/package

      - name: Initialise terraform
        run: terraform init

      - name: Apply terraform
        run: |
          terraform apply \
            -var="discord_public_key=$DISCORD_PUBLIC_KEY" \
            -var="container_repo=${{ env.DOCKER_REPO }}" \
            -var="container_tag=${{ env.DOCKER_TAG }}" \
            -auto-approve
        env:
          DISCORD_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
