name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: carto-discord/carto/.github/workflows/build.yml@main
  lint:
    needs: build
    uses: carto-discord/carto/.github/workflows/lint.yml@main
  unit:
    needs: build
    uses: carto-discord/carto/.github/workflows/unit-test.yml@localstack-integration
  integration:
    needs: build
    uses: carto-discord/carto/.github/workflows/integration-test.yml@localstack-integration
  deploy:
    needs: [unit, integration, lint]
    uses: carto-discord/carto/.github/workflows/deploy.yml@main
    secrets:
      service_account_key: ${{ secrets.GCP_SA_KEY }}
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      discord_public_key: ${{ secrets.PUBLIC_KEY }}
