name: Deploy

on:
  workflow_call:
    inputs:
      app_name:
        default: "carto-bot"
        required: false
        type: string
      node-version:
        default: "16"
        required: false
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      discord_public_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: Initialise terraform
        run: terraform init

      - name: Set up Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      # Needed to get Workspaces in Node 14
      - name: Upgrade NPM
        if: ${{ github.events.inputs.node-version != 16 }}
        run: npm i -g npm

      - uses: hashicorp/setup-terraform@v1

      - name: Install Node dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Build node-canvas libraries
        run: docker build -t canvas-libs .

      - name: Inject libraries
        run: |
          id=$(docker create canvas-libs)
          docker cp $id:/root/dist ./packages/create-map
          docker cp $id:/root/dist ./packages/add-token
          docker cp $id:/root/dist ./packages/move-delete-token
          docker rm -v $id

      - name: Apply terraform
        run: |
          terraform apply \
            -var="app_name=${{ secrets.app_name }}" \
            -var="discord_public_key=${{ secrets.discord_public_key }}" \
            -auto-approve
