name: Deployment

on:
  push:
    branches:
      - main
    paths:
      - "assets/**"
      - "packages/**"
      - ".github/workflows/**"
      - "!packages/terraform/localstack/**"
      - "!packages/terraform/user/**"

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  integration:
    needs: checks
    uses: ./.github/workflows/integration-test.yml
    secrets:
      discord_token: ${{ secrets.BOT_TOKEN }}
  deploy:
    needs: integration
    uses: ./.github/workflows/deploy.yml
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      discord_public_key: ${{ secrets.PUBLIC_KEY }}
      discord_token: ${{ secrets.BOT_TOKEN }}
      contact_email: ${{ secrets.CONTACT_EMAIL }}
