name: Deploy

on:
  workflow_call:
    secrets:
      service_account_key:
        required: true
      project_id:
        required: true
      discord_public_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployment
    env:
      DOCKER_REPO: api
      DOCKER_TAG: latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.service_account_key }}
          project_id: ${{ secrets.project_id }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/${{ secrets.project_id }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}

      - name: Download Client Artifact
        uses: actions/download-artifact@v2
        with:
          name: carto-client
          path: client/package

      - name: Initialise terraform
        run: terraform init

      - name: Apply terraform
        run: |
          terraform apply \
            -var="discord_public_key=$DISCORD_PUBLIC_KEY" \
            -var="container_repo=${{ env.DOCKER_REPO }}" \
            -var="container_tag=${{ env.DOCKER_TAG }}" \
            -auto-approve
        env:
          DISCORD_PUBLIC_KEY: ${{ secrets.discord_public_key }}
