name: Lint

on:
  workflow_call:
    inputs:
      python-version:
        default: "3.10"
        required: false
        type: string
      node-version:
        default: "14"
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set up Node.JS 14
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Lint Client
        working-directory: client
        run: |
          npm ci
          npm run lint

      - name: Lint API/
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
