name: pr-checks

on: pull_request

jobs:
  build:
    uses: carto-discord/carto/.github/workflows/build.yml@main
  lint:
    needs: build
    uses: carto-discord/carto/.github/workflows/lint.yml@main
  test:
    needs: build
    uses: carto-discord/carto/.github/workflows/test.yml@main
