name: pr-checks

on: pull_request

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  integration:
    needs: checks
    uses: ./.github/workflows/integration-test.yml
    secrets:
      discord_token: ${{ secrets.BOT_TOKEN }}
