name: pr-checks

on: pull_request

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  deploy:
    needs: checks
    uses: ./.github/workflows/pr-environment.yml
    with:
      public-key: a58293d7fa04d53ab90108be275a87fe890eece595962273a93e1f87d398df74
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      discord_token: ${{ secrets.BOT_TOKEN }}
  integration:
    needs: deploy
    uses: ./.github/workflows/integration-test.yml
    with:
      # Not actually private, just for testing purposes
      private-key: 814d1a8737ba28a2ae72e39cac46468002525a64e4f002d7b52dd06efb9dc4b8a58293d7fa04d53ab90108be275a87fe890eece595962273a93e1f87d398df74
      map-bucket: carto-bot-pr-${{ github.event.pull_request.number }}-maps
