name: pr-checks

on: pull_request

jobs:
  build:
    uses: carto-discord/carto/.github/workflows/build.yml@main
  lint:
    needs: build
    uses: carto-discord/carto/.github/workflows/lint.yml@main
  unit:
    needs: build
    uses: carto-discord/carto/.github/workflows/unit-test.yml@localstack-integration
  integration:
    needs: build
    uses: carto-discord/carto/.github/workflows/integration-test.yml@localstack-integration
    secrets:
      discord_public_key: ${{ secrets.PUBLIC_KEY }}
