name: pr-checks

on: pull_request

jobs:
  build:
    uses: ./.github/workflows/build.yml
  lint:
    needs: build
    uses: ./.github/workflows/lint.yml
  unit:
    needs: build
    uses: ./.github/workflows/unit-test.yml
  integration:
    needs: build
    uses: ./.github/workflows/integration-test.yml
    secrets:
      discord_token: ${{ secrets.BOT_TOKEN }}
