name: Register Commands

on:
  push:
    branches:
      - main
    paths:
      - "packages/register-commands"
      - ".github/workflows/register-commands.yml"

jobs:
  register:
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Register commands
        run: npm start -w @carto/register-commands
