name: Command Registration

on:
  push:
    branches:
      - main

jobs:
  register:
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install node depedencies
        working-directory: client
        run: npm ci

      - name: Build node application
        working-directory: client
        run: npm run build

      - name: Register Slash Commands
        working-directory: client
        run: npm run register
